//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasCuentasBancarias
    {
        public System.Guid EmpresaCuentaBancariaId { get; set; }
        public Nullable<System.Guid> EmpresaId { get; set; }
        public string EmpresaCuentaBancariaBanco { get; set; }
        public string EmpresaCuentaBancariaNumero { get; set; }
        public string EmpresaCuentaBancariaCCI { get; set; }
        public Nullable<System.Guid> EmpresaCuentaBancariaMoneda { get; set; }
        public Nullable<bool> EmpresaCuentaBancariaPorDefecto { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.Guid> UsuarioActualizacion { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
