//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasDetalles
    {
        public System.Guid FacturaDetalleId { get; set; }
        public Nullable<System.Guid> FacturaId { get; set; }
        public string FacturaDetalleDescripcion { get; set; }
        public Nullable<decimal> FacturaDetalleCantidad { get; set; }
        public Nullable<decimal> FacturaDetallePrecioUnitario { get; set; }
        public Nullable<decimal> FacturaDetalleImporteTotal { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.Guid> UsuarioActualizacion { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
