//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasPagos
    {
        public System.Guid FacturaPagoId { get; set; }
        public Nullable<System.Guid> FacturaId { get; set; }
        public Nullable<System.Guid> PagoId { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
