//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestosItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PresupuestosItems()
        {
            this.OrdenesPartidas = new HashSet<OrdenesPartidas>();
            this.PresupuestosItemsLogs = new HashSet<PresupuestosItemsLogs>();
        }
    
        public System.Guid PresupuestoItemId { get; set; }
        public Nullable<System.Guid> PresupuestoId { get; set; }
        public Nullable<System.Guid> PartidaId { get; set; }
        public Nullable<System.Guid> PadrePartidaId { get; set; }
        public Nullable<System.DateTime> PresupuestoItemFecha { get; set; }
        public string PresupuestoItemCodigo { get; set; }
        public string PresupuestoItemNaturaleza { get; set; }
        public string PresupuestoItemUnidad { get; set; }
        public string PresupuestoItemResumen { get; set; }
        public Nullable<decimal> PresupuestoItemCantidad { get; set; }
        public Nullable<decimal> PresupuestoItemPrecio { get; set; }
        public Nullable<decimal> PresupuestoItemImporte { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.Guid> UsuarioActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesPartidas> OrdenesPartidas { get; set; }
        public virtual Partidas Partidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosItemsLogs> PresupuestosItemsLogs { get; set; }
    }
}
