//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresCuentasBancarias
    {
        public System.Guid ProveedorCuentaBancariaId { get; set; }
        public Nullable<System.Guid> ProveedorId { get; set; }
        public string ProveedorCuentaBancariaBanco { get; set; }
        public string ProveedorCuentaBancariaNumero { get; set; }
        public string ProveedorCuentaBancariaCCI { get; set; }
        public Nullable<System.Guid> ProveedorCuantaBancariaMoneda { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
