//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresContactos
    {
        public System.Guid ProveedorContactoId { get; set; }
        public Nullable<System.Guid> ProveedorId { get; set; }
        public string ProveedorContactoTipo { get; set; }
        public string ProveedorContactoNombres { get; set; }
        public string ProveedorContactoApellidos { get; set; }
        public string ProveedorContactoEmail { get; set; }
        public string ProveedorContactoTelefono { get; set; }
        public string ProveedorContactoCelular { get; set; }
        public Nullable<System.Guid> UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.Guid> UsuarioActualizacion { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
