//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.Ordenes = new HashSet<Ordenes>();
            this.ProveedoresContactos = new HashSet<ProveedoresContactos>();
            this.ProveedoresCuentasBancarias = new HashSet<ProveedoresCuentasBancarias>();
            this.Facturas = new HashSet<Facturas>();
        }
    
        public System.Guid ProveedorId { get; set; }
        public string ProveedorRuc { get; set; }
        public string ProveedorEmail { get; set; }
        public string ProveedorRazonSocial { get; set; }
        public string ProveedorPassword { get; set; }
        public Nullable<System.Guid> ProveedorTipo { get; set; }
        public string ProveedorDireccionFiscal { get; set; }
        public Nullable<int> ProveedorPlazoPago { get; set; }
        public string ProveedorEstado { get; set; }
        public Nullable<System.Guid> ProveedorTipoDetraccion { get; set; }
        public Nullable<decimal> ProveedorPorcentajeDetraccion { get; set; }
        public string ProveedorCuentaDetraccion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.Guid> UsuarioValidacion { get; set; }
        public Nullable<System.Guid> TipoProveedorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes> Ordenes { get; set; }
        public virtual TiposDetracciones TiposDetracciones { get; set; }
        public virtual TiposProveedores TiposProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresContactos> ProveedoresContactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedoresCuentasBancarias> ProveedoresCuentasBancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
