//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectosPresupuestos
    {
        public System.Guid ProyectoPresupuestoId { get; set; }
        public Nullable<System.Guid> ProyectoId { get; set; }
        public Nullable<System.Guid> PresupuestoId { get; set; }
    
        public virtual Presupuestos Presupuestos { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
