//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortonMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nortonEntities : DbContext
    {
        public nortonEntities()
            : base("name=nortonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<EmpresasCuentasBancaria> EmpresasCuentasBancarias { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<FacturasDetalle> FacturasDetalles { get; set; }
        public virtual DbSet<FacturasEstado> FacturasEstados { get; set; }
        public virtual DbSet<FacturasGuiasRemision> FacturasGuiasRemisions { get; set; }
        public virtual DbSet<FacturasOrdene> FacturasOrdenes { get; set; }
        public virtual DbSet<FacturasPago> FacturasPagos { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<Ordene> Ordenes { get; set; }
        public virtual DbSet<OrdenesDetalle> OrdenesDetalles { get; set; }
        public virtual DbSet<OrdenesPartida> OrdenesPartidas { get; set; }
        public virtual DbSet<Pagina> Paginas { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<ParametrosDetalle> ParametrosDetalles { get; set; }
        public virtual DbSet<Partida> Partidas { get; set; }
        public virtual DbSet<Presupuesto> Presupuestos { get; set; }
        public virtual DbSet<PresupuestosItem> PresupuestosItems { get; set; }
        public virtual DbSet<PresupuestosItemsLog> PresupuestosItemsLogs { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<ProveedoresContacto> ProveedoresContactos { get; set; }
        public virtual DbSet<ProveedoresCuentasBancaria> ProveedoresCuentasBancarias { get; set; }
        public virtual DbSet<Proyecto> Proyectos { get; set; }
        public virtual DbSet<ProyectosPresupuesto> ProyectosPresupuestos { get; set; }
        public virtual DbSet<ProyectosResponsable> ProyectosResponsables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesPagina> RolesPaginas { get; set; }
        public virtual DbSet<TiposdeCambio> TiposdeCambios { get; set; }
        public virtual DbSet<TiposDetraccione> TiposDetracciones { get; set; }
        public virtual DbSet<TiposFactura> TiposFacturas { get; set; }
        public virtual DbSet<TiposProveedore> TiposProveedores { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
