//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortonMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrdenesDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesDetalle()
        {
            this.OrdenesPartidas = new HashSet<OrdenesPartida>();
        }
    
        public System.Guid OrdenDetalleId { get; set; }
        public Nullable<System.Guid> OrdenId { get; set; }
        [Display(Name="Item")]
        [Required]
        public Nullable<int> OrdenDetalleItem { get; set; }
        [Display(Name="Descripción")]
        [Required]
        public string OrdenDetalleDescripcion { get; set; }
        [Display(Name="Cuotas")]
        [Required]
        public Nullable<int> OrdenDetalleCuotas { get; set; }
        [Required]
        [Display(Name ="Unidad")]
        public string OrdenDetalleUnidad { get; set; }
        [Required]
        [Display(Name ="Precio Unitario")]
        public Nullable<decimal> OrdenDetallePrecioUnitario { get; set; }
        [Display(Name="Precio Total")]
        [Required]
        public Nullable<decimal> OrdenDetallePrecioTotal { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.Guid> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.Guid> UsuarioActualizacion { get; set; }
    
        public virtual Ordene Ordene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesPartida> OrdenesPartidas { get; set; }
    }
}
