//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortonMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasOrdene
    {
        public string FacturaOrdenId { get; set; }
        public Nullable<System.Guid> FacturaId { get; set; }
        public Nullable<System.Guid> OrdenId { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Ordene Ordene { get; set; }
    }
}
