//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortonMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturasDetalles = new HashSet<FacturasDetalle>();
            this.FacturasEstados = new HashSet<FacturasEstado>();
            this.FacturasGuiasRemisions = new HashSet<FacturasGuiasRemision>();
            this.FacturasOrdenes = new HashSet<FacturasOrdene>();
            this.FacturasPagos = new HashSet<FacturasPago>();
            this.Proveedores = new HashSet<Proveedore>();
        }
    
        public System.Guid FacturaId { get; set; }
        public Nullable<System.Guid> FacturaProyecto { get; set; }
        public Nullable<System.Guid> FacturaTipo { get; set; }
        public string FacturaSerie { get; set; }
        public string FacturaNumero { get; set; }
        public Nullable<System.DateTime> FacturaFechaEmision { get; set; }
        public Nullable<System.DateTime> FacturaFechaVencimiento { get; set; }
        public Nullable<System.Guid> FacturaMoneda { get; set; }
        public string FacturaEstado { get; set; }
        public Nullable<decimal> FacturaSubtotal { get; set; }
        public Nullable<decimal> FacturaIgv { get; set; }
        public Nullable<decimal> FacturaImporteTotal { get; set; }
        public Nullable<decimal> FacturaFondoGarantia { get; set; }
        public Nullable<decimal> FacturaPorcentajeDetraccion { get; set; }
        public Nullable<decimal> FacturaMontoDetraccion { get; set; }
        public Nullable<decimal> FacturaImportePagar { get; set; }
        public string FacturaUrl { get; set; }
        public Nullable<System.DateTime> FacturaFechaPagoProgramada { get; set; }
    
        public virtual TiposFactura TiposFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasDetalle> FacturasDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasEstado> FacturasEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasGuiasRemision> FacturasGuiasRemisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasOrdene> FacturasOrdenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasPago> FacturasPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedore> Proveedores { get; set; }
    }
}
