//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortonMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesPartida
    {
        public System.Guid OrdenPartidaId { get; set; }
        public Nullable<System.Guid> OrdenId { get; set; }
        public Nullable<System.Guid> ProyectoId { get; set; }
        public Nullable<System.Guid> PresupuestoItemId { get; set; }
        public Nullable<System.Guid> OrdenDetalleId { get; set; }
    
        public virtual OrdenesDetalle OrdenesDetalle { get; set; }
        public virtual PresupuestosItem PresupuestosItem { get; set; }
    }
}
