//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NortonMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPagina
    {
        public System.Guid RolId { get; set; }
        public System.Guid PaginaId { get; set; }
        public string Accion { get; set; }
    
        public virtual Pagina Pagina { get; set; }
        public virtual Role Role { get; set; }
    }
}
